### PR TITLE
Batoption equality

### PR DESCRIPTION
**Pull request by gregory-nisbet**
Hi everyone,

I added an implementation for `BatOption.equal`, based on the function in `BatSeq` which seems to be the most general API for a function called `equal` in the project. 

I also added a test in the non-property-based portion in the test suite.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Looks useful, thanks.
Can you inline the tests in batOption.ml rather than adding a new file.
The unit test should be about four lines this way.

**Comment by gregory-nisbet** [comment]
@UnixJunkie 

On further inspection, `equal` is an exact duplicate of the function `BatOptiol.eq` which already exists.

I'm not sure what I should do. I got the task from the list of low hanging fruit for new people.

**Comment by UnixJunkie** [comment]
Ok, let's close this PR then.
Sorry.
Where did you get the page of low hanging fruits?
The bug tracker
https://github.com/ocaml-batteries-team/batteries-included/issues
has many things.
Maybe it is more up to date and you can pick something from it.

**Comment by gregory-nisbet** [comment]
Ici:

https://github.com/ocaml-batteries-team/batteries-included/wiki/%22Junior-tasks%22-for-batteries

It might still be useful to create an `equal` alias for `eq` to bring it in line with the other modules.

Does Batteries have general-purpose interfaces for `equal-able`, `comparable`, &c things?

Also, thank you for the link to the bug tracker.

**Comment by UnixJunkie** [comment]
If many other modules have an equal, then an alias looks like a good idea.
But other maintainers might voice differently.

**Pull request closed without merging**
