### PR TITLE
A couple of critical fixes in Map.update

### PR DESCRIPTION
**Pull request by murmour**
Two separate issues are fixed by two separate commits, which should be self-explanatory.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
wasn't there a unit test supposed to catch this already?
Is the test broken / never launched?

**Comment by murmour** [comment]
Tests were not comprehensive enough.

Also, I suppose that no one has _ever_ used this function.

**Comment by UnixJunkie** [comment]
It was probably added to reflect BatSet.update (by me).
Nice catch.
I am in favour of merging this, unless @gasche has some objections.

**Comment by UnixJunkie** [comment]
Can you send a fix for BatSet.update too?
I think it suffers from the same problem.

**Comment by murmour** [comment]
Indeed, BatSet.update suffers from one of these issues. I have added a fix for that.

**Comment by UnixJunkie** [comment]
I confirm the new tests are passing.
Thanks for the fix in BatSet also.

**Comment by gasche** [comment]
Thanks!

**Pull request merged**
