### PR TITLE
BatSet.at_rank_exn

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by gasche** [comment]
It's a bit hard to review the code because you committed the `.ml` files produced by the `.mlv`. Could you remove those, and maybe rebase the PR in one or two self-contained commits (that will be useful at merge-time anyway)?

**Comment by UnixJunkie** [comment]
I tried in here:
https://github.com/ocaml-batteries-team/batteries-included/pull/626

**Comment by gasche** [comment]
Thanks! (Next time you can just `git push -f` to your PR branch and github will update the PR)

**Comment by UnixJunkie** [comment]
You closed but it's not merged ?

**Comment by gasche** [comment]
I just closed the "old" PR, and will review and continue discussion in the "new" PR #626.

**Pull request closed without merging**
