### PR TITLE
added to_rev_seq to map, splay and set

### PR DESCRIPTION
**Pull request by jabot2**

### CODE REVIEW

**Comment by jabot2** [comment]
This PR is not enough to achieve compatibility with 4.12 though.
```
File "src/batteries_compattest.ml", line 119, characters 53-59:
119 |   let _ = assert ([1,1;2,2;3,3;] = (sort_map (module IntMap) [3; 1; 2;]))
                                                           ^^^^^^
Error: Signature mismatch:
       ...
       Type declarations do not match:
         type 'a t = 'a BatMap.Int.t
       is not included in
         type +!'a t
       Their variances do not agree.
       File "map.mli", line 70, characters 4-15: Expected declaration
       File "src/batMap.mli", line 76, characters 2-14: Actual declaration

```

Annoyingly, the new syntax for variances is not backwards compatible, i.e. writing `type +!a t = ...` won't compile on e.g. 4.02.

**Comment by kit-ty-kate** [comment]
The Map.t type could simply be conditionally written with and without the injectivity annotation using batteries' prepocessor. e.g.
```
##>=4.12 type +!'a t ...
##<4.12 type +'a t ...
```

**Comment by jabot2** [comment]
@kit-ty-kate is it possible to add those annotations to a .ml / .mli file? or do the files need to be renamed?

**Comment by UnixJunkie** [comment]
Use this:
```ocaml
type +
##V>=4.12## !
'a t ...
```

**Comment by UnixJunkie** [comment]
If it's a .mli file, it will need to be renamed .mliv.
If it's a .ml file --> .mlv.

**Comment by UnixJunkie** [comment]
I will try to merge this tonight and fix what's needed; don't bother and thanks a lot for contributing this.

**Review by gasche — APPROVED** [review]
The code is fine. Thanks!

**Pull request merged**
