### PR TITLE
BatSet.pop max

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by gasche** [comment]
Given that this PR supersedes #618 , maybe we could close #618 and consider this PR the one true place for pop-related changes?

**Comment by gasche** [comment]
The code is in mergeable state.

Could we have `pop_{minx,max}` in `Map` as well? Would it be reasonable as part of this PR, or would you rather merge this now and open a separate PR?

**Comment by UnixJunkie** [comment]
It will be a separate PR.
I track it here so that I don't forget it:
https://github.com/ocaml-batteries-team/batteries-included/issues/622
Maybe next week I will have time for it.

**Comment by UnixJunkie** [comment]
Can this be merged?

**Pull request merged**
