### PR TITLE
Add equality between Stdlib.result and BatInnerPervasives.result

### PR DESCRIPTION
**Pull request by facelesspanda**
See #938 

I agreed with the point raised by the issue author. I don't think more changes are needed. If I missed some places to put tests, I'd like to know.

### CODE REVIEW

**Comment by rixed** [comment]
According to OCaml "Changes" file, the result type appeared in OCaml v4.08.

**Comment by facelesspanda** [comment]
okay, I see. Makes sense. Thanks, I'll do that.

**Comment by UnixJunkie** [comment]
A possible test is to opam switch to 4.07 and compile batteries, then switch to 4.08 and recompile.
I am not sure if it is possible to unit-test this.

**Comment by hcarty** [comment]
The `result` type appeared in 4.03. A `Result` module was added in 4.08.

**Comment by facelesspanda** [comment]
so, no need to change the type definition?
Though I may have to remove the compatibility with `Legacy.Result`, right? because before 4.07 that module doesn't exist?

**Comment by UnixJunkie** [comment]
For things which are version-dependant, you can use preprocessor directives, as stated before by rixed.

**Comment by facelesspanda** [comment]
As a matter of fact, the compatibility with the `Stdlib.Result` module fails because `Stdlib.Seq.t` is not `BatSeq.t`. I'll look into that too.

**Comment by rixed** [comment]
Superseeded by https://github.com/ocaml-batteries-team/batteries-included/pull/957

**Pull request closed without merging**
