### PR TITLE
fix in the Makefile for when *.cmt{i} files are not produced by ocaml…

### PR DESCRIPTION
**Pull request by UnixJunkie**
…build

### CODE REVIEW

**Comment by UnixJunkie** [comment]
That's for the release.
I'll have to retag if this fix is accepted.

**Comment by gasche** [comment]
When does the "not produced" situation happen, don't we pass `-bin-annot` all the time? How did you notice the issue?

**Comment by UnixJunkie** [comment]
we pass bin_annot in _flags, but old versions of ocamlbuild don't understand it (and just ignore it).
@yallop spotted that make install failed in the Travis CI tests for the new batteries opam package there: https://github.com/ocaml/opam-repository/pull/8942
Maybe there is a fix via myocamlbuild.ml but I don't want to venture in such lands (I'd rather like to change the build system altogether).

**Comment by gasche** [comment]
Come on, the `myocamlbuild.ml` fix is trivial. I'll send a PR.

**Comment by gasche** [comment]
But in fact the problem remains: `-bin-annot` was only added to 4.00 so if we want to support 3.12.1 (which is a good idea; Red Hat people still support it) we need to be robust to the absence of `.cmt*` files anyway.

**Comment by gasche** [comment]
PR in #749. I think we should merge both.

**Pull request merged**
