### PR TITLE
Add functions added in OCaml 4.10

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Fixes https://github.com/ocaml-batteries-team/batteries-included/issues/935.

This can be viewed as a first step, some of the functions can be reproduced in batteries to avoid them being available only with OCaml 4.10

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Hi Kate, Cc: @rixed,
No hard feelings if we ask you to resend this PR against master
once V3 is the new master?
Because, accepting this PR will force us to do yet another minor release.
While, we already anounced the latest minor release was the last.
The next release will be a major one.
Thanks,
F.

**Comment by UnixJunkie** [comment]
@kit-ty-kate no comment?
Regards,
F.

**Comment by kit-ty-kate** [comment]
I don't mind at all (sorry for not responding)

**Comment by kit-ty-kate** [comment]
Would it be ok to merge this PR now and do a release soon? The release for 4.10.0 is planned for Monday afaik (delays may apply)

**Comment by UnixJunkie** [comment]
I can merge right now.
For the "new release soon", I am not sure since it is a major release.

**Comment by UnixJunkie** [comment]
Maybe @rixed might be interested in doing the next release.

**Comment by kit-ty-kate** [comment]
For the record I can take care of submitting the release to opam-repository once a tag is available, if you prefer.

**Comment by rixed** [comment]
I have no interest in packaging, it's just toil that I do only when I need it. I'm generally happy when others do it, but I would also agree to do it regularly so this does not always fall onto the same persons.
That said, I could find time next week to do a release.

**Comment by rixed** [comment]
Here is an error that's detected by `make test`:

```
File "src/batteries_compattest.ml", line 38, characters 17-21:
38 |   module List = (List: module type of Legacy.List)
                      ^^^^
Error: Signature mismatch:
       ...
       Values do not match:
         val find_map : ('a -> 'b option) -> 'a list -> 'b
       is not included in
         val find_map : ('a -> 'b option) -> 'a list -> 'b option
       File "list.mli", line 240, characters 0-55: Expected declaration
       File "src/batList.mliv", line 461, characters 0-49: Actual declaration
```

**Comment by kit-ty-kate** [comment]
arf right, sorry. I have a fix.

**Pull request merged**
