### PR TITLE
change the way OCaml5's Stdlib module is supported (replacing Pervasives)

### PR DESCRIPTION
**Pull request by UnixJunkie**
I try to not put all files under pre-processing to minimize the change.
The previous way it was managed was not compiling for ocaml<5.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
@sim642 I had to change the way the new Stdlib module from ocaml5 is handled.
Because the previous way was not compiling with ocaml < 5.

**Comment by UnixJunkie** [comment]
I feel only the changes in BatHeap and BatInt might need to be reviewed (because they have a risk of introducing bugs).
All the rest is just trivial.

**Comment by UnixJunkie** [comment]
Now, all tests are passing on both ocaml 4.02.3 and 5.0.0~alpha1.
This is a lot of small stupid changes.

**Comment by sim642** [comment]
> I feel only the changes in BatHeap and BatInt might need to be reviewed (because they have a risk of introducing bugs).
> All the rest is just trivial.

According to git blame, a few of those touch the code from #278, but that fix remains, so it looks fine.

Was about to ask about all the `$inject` stuff, but apparently that's a qtest thing.

**Comment by UnixJunkie** [comment]
Yes, inject is to make qtest aware of some global things.

**Comment by UnixJunkie** [comment]
Thanks for the review.

**Pull request merged**
