### PR TITLE
add new Either module if OCaml >= 4.12

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Maybe, we should copy-paste the .ml file from the stdlib directly, and not make this new module conditional on the ocaml version.

**Comment by UnixJunkie** [comment]
@gasche what do you think?

**Comment by gasche** [comment]
Indeed, you should not use a `V>=4.12` conditional for this module, as it works with older OCaml versions. (Same for `List.partition_map`.)

**Comment by UnixJunkie** [comment]
ok, I'll change that.

**Comment by UnixJunkie** [comment]
Shouldn't we have added a constraint to specify that Eiter.t = BatEither.t, somehow?
For ocaml >= 4.12.

**Comment by UnixJunkie** [comment]
I'll send a PR, we have the same constrain in BatSeq.

**Pull request merged**
