### PR TITLE
Hash functions

### PR DESCRIPTION
**Pull request by c-cube**
Early draft for #492, as simple as possible (and even more). I just implemented hash functions for a few modules, but it should be easy to do so for other structures (e.g. `BatLazyList` or `Tuple2`, `Tuple3`...).

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Is this really needed?
I am not against it but I am not a specialist of hashing either.

**Comment by UnixJunkie** [comment]
We should do a vote, or we should go vote, depending on where you live.

**Comment by UnixJunkie** [comment]
I am not qualified to review this PR: if I don't use a Hashtbl.t, then I don't hash anything.
Note however that this PR was submitted by a very skilled hacker.
We should probably merge it.

**Comment by c-cube** [comment]
probably no need for that, unless someone shows up here and asks for the feature :slightly_smiling_face:

**Pull request closed without merging**
