### PR TITLE
Remove ocamlbuild

### LINKED ISSUE #658: get rid of the .mlv/.mliv files

### LINKED ISSUE #1101: get rid of ocamlbuild

### PR DESCRIPTION
**Pull request by sim642**
In #1109 dune became the default build tool, so this removes most of the ocamlbuild stuff. Closes #1101.

With ocamlbuild compatibility no longer needed, preprocessing is also simplified. Closes #658.

There's still a bunch of old ocamlbuild-related things in the `build` directory but I think they weren't even used before. So I didn't do a full clean-up because I'm not sure what all of it is and has been used for.

I did these things a long time ago, but never opened a PR. Not sure if I still intended to do something.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I will review and test it.
If that works, next step I would like to rename all .mlv/mliv files to .ml/mli.
This specific extension has _always_ annoyed me.

**Comment by UnixJunkie** [comment]
You already did that! Yummy yummy.

**Comment by UnixJunkie** [comment]
The test_install target in the Makefile was useful.

So, dune still cannot compile an exe with a one-liner invocation?
The only feature ocamlbuild can be praised for...

**Comment by UnixJunkie** [comment]
Our test suite does not run w/ ocaml 4.02.3, but I think this is not new.

**Comment by UnixJunkie** [comment]
'make doc' does not work in this branch.
It produces many errors.

**Comment by UnixJunkie** [comment]
Apparently, make doc should be preceded by make.
Strange this is not already encoded in the Makefile.

**Comment by UnixJunkie** [comment]
@sim642 can you check the 'make doc' target is still doing what it should.
I merged; but I am not sure about this one.

**Comment by sim642** [comment]
> The test_install target in the Makefile was useful.
> 
> So, dune still cannot compile an exe with a one-liner invocation? The only feature ocamlbuild can be praised for...

It should be able to. I might've just not noticed the test_install target being different from all the other testing targets. I'll try to add it back.


> make doc' does not work in this branch (I tried under ocaml-5.0.0).
> It produces many errors.



> Apparently, make doc should be preceded by make.
> Strange this is not already encoded in the Makefile.

I recall many odoc warnings not really being an issue but I'll look into it for #1093. I have some old branch also related to fixing some odoc warnings, so I should dig that up. And I think dune should be able to build the docs without explicitly building the code before.

**Comment by UnixJunkie** [comment]
It is possible the odoc errors are just warnings; but I am not sure and it is still annoying.
If our doc is meant to be generated by odoc from now on, then we should use it properly.
Throwing many warnings might hide some things which are actually errors; people should not get used to living with
code throwing many warnings.

**Comment by sim642** [comment]
> The test_install target in the Makefile was useful.
> 
> So, dune still cannot compile an exe with a one-liner invocation? The only feature ocamlbuild can be praised for...

I looked into it now and see what you meant. Indeed I think it also requires a very basic `dune` file.

But actually with that, dune with its support for vendoring and monorepos will actually find the batteries library from the workspace even when it's not installed into the opam switch. So it wouldn't test what the script is supposed to be testing. I guess it can just remain like that for now.

**Comment by UnixJunkie** [comment]
Yes, I uncommented this test_install make target (that you previously commented out).
So, it behaves as before and still uses ocamlbuild for the moment.
But, since this is only useful to people who run some tests before a batteries release, no big deal.

**Pull request merged**
