### PR TITLE
Added a combination generator for Enum

### PR DESCRIPTION
**Pull request by Chimrod**
Implement an enumeration over combination #503

This an implementation of mathematical Combination ( https://en.wikipedia.org/wiki/Combination ), wich work with or without repetitions.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
The ocamldoc should have some examples, so that typical use cases can be understood.

**Comment by UnixJunkie** [comment]
And, I'll leave it to fans of the Enum module to decide if new things must be added in it.

**Comment by rixed** [comment]
I vote for it.

**Comment by rixed** [comment]
5 years later I think this is still desirable. Are there objections for merging this?

**Comment by UnixJunkie** [comment]
The corresp. ChangeLog entry is missing.
Appart from this, it looks OK to merge.

**Pull request merged**
