### PR TITLE
List.sum [] is now 0

### LINKED ISSUE #519: List.sum fails on empty list
Strangely, `List.sum` fails on the empty list (instead of returning 0), but `Enum.sum` returns 0 in this case (same for `fsum`).

I guess this will have to wait until 3.0, but still, it's strange.

### PR DESCRIPTION
**Pull request by rixed**
And similarly for fsum.

Closes #519

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I would prefer that '0.0' is used rather than '0.'.
Because, '0.0' is more explicit/easier to read (you don't miss easily that there is a '.' then).

**Comment by rixed** [comment]
If you can't spot the trailing dots then you will have a hard time with floats in OCaml, as every float operators end with a dot. :)
This source file already have plenty of literal `0.` for only a handful of `0.0` so I think it's OK.

**Comment by UnixJunkie** [comment]
Improving the code quality little by little does not hurt.

**Comment by rixed** [comment]
True, but quality is also about consistency. I'll do a global sed later for that.

**Pull request merged**
