### PR TITLE
Make BatResult a superset of OCaml new Result module.

### LINKED ISSUE #839: Result.result type incompatible with ocaml Pervasives.result
Hello, 
I noticed the Batteries result type:
```
 type ('a, 'b) BatPervasives.result =
  | Ok  of 'a
| Bad of 'b
```
is incompatible with OCaml Pervasives.result type :
```
 type ('a, 'b) Pervasives.result =
  | Ok  of 'a
 | Error of 'b
```
Which make it difficult to use a library not using batteries. 
(In fact I stumbled upon an error caused by this months ago and just realised where the problem was).
Is there any reason for this ? Although modifying the entire Batteries to take this into account might be overkill, it would make things more usable.

### PR DESCRIPTION
**Pull request by rixed**
Breaks compatibility with previous versions by renaming our Result.Bad into
OCaml new Result.Error.

Closes #839

### CODE REVIEW

**Comment by UnixJunkie** [comment]
@rixed if we do a major release, there is a v3 branch in batteries' git, that should be merged into master. I never touched this branch, but I think @gascher was maintaining it.

**Comment by rixed** [comment]
I've just suggested we merge master and v3 (into v3 for now)

**Comment by UnixJunkie** [comment]
ok

**Comment by UnixJunkie** [comment]
This PR needs to be ressent to the v3 branch, maybe?

**Comment by rixed** [comment]
Yes I have this ready but I'd like v3 fixed with https://github.com/ocaml-batteries-team/batteries-included/pull/921 first.

**Comment by rixed** [comment]
Reopening the PR against v3 to avoid conflicts.

**Pull request closed without merging**
