### PR TITLE
added BatList.frange

### PR DESCRIPTION
**Pull request by UnixJunkie**
should be quite useful to scientific programmers.
It's the second time that I identify that I need this in a project, so here it is.

### CODE REVIEW

**Comment by gasche** [comment]
What's the reason for asking `To/Downto` instead of inferring it from whether `start <= stop` or `start >= stop`?

**Comment by UnixJunkie** [comment]
I tried to match the interface of BatList.range (which I added long time ago).
Also, in scientific code it doesn't hurt to be very explicit about what you are trying to do.

**Comment by gasche** [comment]
Oh, sure. Merged, thanks!

**Comment by gasche** [comment]
I added a Changes entry in 4720636ae66a1cbdf9bb75201fef0bb755e3df05.

**Comment by UnixJunkie** [comment]
thanks for the review and the changelog update

**Pull request merged**
