### PR TITLE
added BatList.favg

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by gasche** [comment]
Could you write it with a `while` loop and a float reference?
This version allocates a floating box on each list element.

**Comment by UnixJunkie** [comment]
done for favg

**Comment by UnixJunkie** [comment]
done for fsum

**Comment by gasche** [comment]
You may want to run a benchmark to compare your version with one with a `while` loop, such as:

```
let favg l =
  match l with
  | [] -> invalid_arg "Empty List"
  | x::xs ->
    let acc = ref x in
    let len = ref 1 in
    let rem = ref xs in
    let go = ref true in
    while !go do
        match !rem with
        | [] -> go := false;
        | x::xs ->
          acc := !acc +. x;
          incr len;
          rem := xs
      done;
      !acc /. float_of_int !len
```

**Comment by UnixJunkie** [comment]
I have other things to do than running benchmarks.
If there are volunteers, please go ahead.
@gasche if you know that this is more efficient, then you can push such code. I personally don't write code that looks like the output of a compiler.

**Comment by gasche** [comment]
Also, it would be nice if the failure case carried the function name in the exception message.

**Comment by UnixJunkie** [comment]
I added function names to exception messages.

**Comment by UnixJunkie** [comment]
this would be cool to have this in the next release

**Comment by UnixJunkie** [comment]
I will send a link to some benchmarks.
Apparently: fsum_opt is 15% faster than fsum_naive.
favg_opt is 45% faster than favg_naive.

**Comment by UnixJunkie** [comment]
cf. https://github.com/UnixJunkie/batlist_bench_01

**Comment by UnixJunkie** [comment]
superseded by https://github.com/ocaml-batteries-team/batteries-included/pull/746

**Pull request closed without merging**
