### PR TITLE
Fix `dune runtest`

### PR DESCRIPTION
**Pull request by sim642**
Follow-up to #1098 and towards #738.

The main thing is that dune's `inline_tests` runs the qtest backend on the unpreprocessed files (probably because other inline test backends are based on ppx). The solution is to first run `qtest extract` and pipe the result through `prefilter`.
This order is different from Makefile/ocamlbuild, thus the `$inject` changes to move `##V>=5##` only inside. Luckily only parts that are affected are from #1087.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
If I run 'make test', it tells me 2115 tests were ran and OK, then 313 tests ran and OK.

**Comment by UnixJunkie** [comment]
'dune runtest' on the other hand, just tells me 313 tests were ran and OK.

**Comment by UnixJunkie** [comment]
Currently, 'dune runtest' also produces an error:
```
File "src/.batteries.inline-tests/inline_test_runner_batteries.ml-gen", line 13, characters 20-30:
13 | module Pervasives = Pervasives[@warning "-3"]
                         ^^^^^^^^^^
Error (warning 49 [no-cmi-file]): no cmi file was found in path for module Pervasives
```
Can this be corrected?

**Comment by sim642** [comment]
> If I run 'make test', it tells me 2115 tests were ran and OK, then 313 tests ran and OK.

> 'dune runtest' on the other hand, just tells me 313 tests were ran and OK.

That might be due to dune not rerunning things without changes. On a clean run I do get both:

```console
simmo@roentgenium:~/dev/batteries-included (dune-runtest)$ dune clean
simmo@roentgenium:~/dev/batteries-included (dune-runtest)$ dune runtest
.........................................................................................................................................................................................................................................................................................................................
Ran: 313 tests in: 4.02 seconds.
OK
random seed: 213784516                 
Ran: 2115 tests in: 8.77 seconds.                                              
SUCCESS
```

**Comment by sim642** [comment]
> Currently, 'dune runtest' also produces an error:
> 
> ```
> File "src/.batteries.inline-tests/inline_test_runner_batteries.ml-gen", line 13, characters 20-30:
> 13 | module Pervasives = Pervasives[@warning "-3"]
>                          ^^^^^^^^^^
> Error (warning 49 [no-cmi-file]): no cmi file was found in path for module Pervasives
> ```
> 
> Can this be corrected?

Good catch! I forgot to check everything on OCaml 5, but it should be fixed now.

**Comment by UnixJunkie** [comment]
thanks for the update and additional fixes.
'dune runtest' is about four times faster than 'make test' !
Both from a fresh checkout, with nothing compiled.

**Comment by UnixJunkie** [comment]
Also, both targets are still working, which is reassuring.

**Comment by UnixJunkie** [comment]
'make test' AND 'dune runtest' are supposed to work for ocaml<5 and ocaml>=5.
If you find that it is not the case, please tell, or even better, send a PR with a fix. :)

I guess that in the future, we might drop the Makefile.
But, for that, we would need dune to install and do everything fine for the lowest ocaml version we support.

**Pull request merged**
