### PR TITLE
added BatString.count_char

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
please consider merging this one before the new release

**Comment by gasche** [comment]
I'm worried that the `fold` version is going to be sensibly slower than just a loop incrementing a reference.

**Comment by UnixJunkie** [comment]
OK, I'll try to do some tests when I have time

**Comment by UnixJunkie** [comment]
@c-cube Simon, any idea on this?

**Comment by c-cube** [comment]
I don't think the `fold` should be slower, if the accumulator is just an unboxed integer, especially with flambda? But benchmarks are always good.

**Comment by UnixJunkie** [comment]
```
open Core
open Core_bench

module S = struct

  include BatString

  let count_char_fold str char =
    fold_left (fun acc c ->
        if c = char then
          acc + 1
        else
          acc
      ) 0 str

  let count_char_while str char =
    let count = ref 0 in
    let n = length str in
    for i = 0 to n - 1 do
      if (unsafe_get str i) = char then
        incr count
    done;
    !count

end
    
let () =
  Command.run (Bench.make_command [
    Bench.Test.create ~name:"fold_ver" 
      (fun () -> S.count_char_fold "tototititata" 't');
    Bench.Test.create ~name:"while_ver" 
      (fun () -> S.count_char_while "tototititata" 't');
  ])
```

**Comment by UnixJunkie** [comment]
```
# ./_build/default/benchit.exe
Estimated testing time 20s (2 benchmarks x 10s). Change using -quota SECS.
┌───────────┬──────────┬─────────┬────────────┐
│ Name      │ Time/Run │ mWd/Run │ Percentage │
├───────────┼──────────┼─────────┼────────────┤
│ fold_ver  │  51.10ns │  12.00w │    100.00% │
│ while_ver │  14.45ns │         │     28.28% │
└───────────┴──────────┴─────────┴────────────┘
```

**Comment by UnixJunkie** [comment]
I updated the PR accordingly.
It should be merged by another maintainer.

**Comment by UnixJunkie** [comment]
thanks

**Pull request merged**
