### PR TITLE
Fix unit tests v3

### PR DESCRIPTION
**Pull request by rixed**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Why the PR has changes in BatResult.ml{i} which are not unit tests related?
Github lagging?

**Comment by rixed** [comment]
> Why the PR has changes in BatResult.ml{i} which are not unit tests related?
> Github lagging?

Because of a problem in between the chair and the keyboard.
The first commit was meant to be sent separately.

**Comment by rixed** [comment]
Looks better now.

**Comment by UnixJunkie** [comment]
ok, thanks.

**Pull request merged**
