### PR TITLE
Fix tests on OCaml 4.10 (alt fix)

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Opening this one just in case to see more clearly the changes between https://github.com/ocaml-batteries-team/batteries-included/pull/943 and this

cc @rixed

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Is travis not enabled?

**Comment by UnixJunkie** [comment]
The travis thing is broken for quite some time.

**Comment by kit-ty-kate** [comment]
This should still be merged though

**Comment by UnixJunkie** [comment]
I thought @rixed fixed the tests for 4.10 very recently...

**Comment by rixed** [comment]
On current master (aka without this fix):
```
$ make test
...
File "src/batteries_compattest.ml", line 38, characters 17-21:
38 |   module List = (List: module type of Legacy.List)
                      ^^^^
Error: Signature mismatch:
       ...
       Values do not match:
         val find_map : ('a -> 'b option) -> 'a list -> 'b
       is not included in
         val find_map : ('a -> 'b option) -> 'a list -> 'b option
       File "list.mli", line 240, characters 0-55: Expected declaration
       File "src/batList.mliv", line 461, characters 0-49: Actual declaration
Command exited with code 2.
Compilation unsuccessful after building 194 targets (192 cached) in 00:00:00.
make: *** [Makefile:252: test-compat] Error 10
```

With the fix:
```
$ git merge kit-ty-kate/fix-410-alt
(...)
$ make test
Ran: 234 tests in: 6.45 seconds.
OK
```

So this patch is indeed fixing this issue.

**Comment by UnixJunkie** [comment]
thanks for the test!

**Comment by rixed** [comment]
Shall we move the v3.0.0 tag then?

**Comment by kit-ty-kate** [comment]
> Shall we move the v3.0.0 tag then?

That will have to be `v3.0.1`. `v3.0.0` has already been released in opam-repository.

**Comment by rixed** [comment]
Ah OK I was unaware of this.

**Comment by UnixJunkie** [comment]
Since it is just a fix for tests, as far as I understand, I don't think we need to issue a new tag and release again.

**Pull request merged**
