### PR TITLE
V3

### LINKED ISSUE #932: make v3 the new master
And have a maintenance branch named v2 or 2.x or whatever, for any upcoming fixes on the v2.
WDYT?
Have some time to do it quickly if everybody agree.

### PR DESCRIPTION
**Pull request by rixed**
Merge with latest master.
Please check that it is OK, and then let's make this master.
Notice that I've already pushed a v2 at v2.11.0

Closes #932

### CODE REVIEW

**Comment by rixed** [comment]
I don't know why this patch look so big here.
If you diff ocaml-batteries-team's v3 with mine you should ses that there is only one patch touching 4 files (a big merge has been performed not so long ago already).

**Comment by rixed** [comment]
Can we complete this move before more commits are added to master, requiring a new rebase?

**Comment by UnixJunkie** [comment]
I am ok to merge it.
I just need to ask something to someone before.

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/pull/936
in case we merge

**Comment by UnixJunkie** [comment]
Please proceed with the renaming of branches, etc.

**Comment by rixed** [comment]
Done.
the v2 branch is now at the head of the v2 maintenance branch.
master is now where v3 was.
the v3 branch is no more.

Welcome in batteries v3!

**Pull request merged**
