### PR TITLE
Add note explaining that BatX is also Batteries.X

### PR DESCRIPTION
**Pull request by mars0i**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I guess this is only true after en 'open Batteries' directive

**Comment by mars0i** [comment]
You mean before `open Batteries`?  Yes.  I took that to be implied by what I wrote.  I would be happy to write a bit more there.  The existing document is very brief at the top, so I was following that pattern.  A bit more explanation about `open` would be friendlier, though.  Leaving it implicit is less friendly, I would think, but means more text to scroll past to get to the modules.

**Comment by mars0i** [comment]
Oh, forgot to mention that this for #784 .

**Comment by mars0i** [comment]
I revised the statement to add a brief comment about what happens when `Batteries` has been `open`ed.  I meant for it to be a separate PR.  I forgot that you can't do that, so I guess I added a commit to the PR.  Anyway, this is a small PR, so it will be easy to edit if the Batteries team wants something different.

**Comment by gasche** [comment]
You could give an example: "For example, `BatList` can also be used as `Batteries.List`."

**Comment by gasche** [comment]
Merged, thanks!

**Pull request merged**
