### PR TITLE
BatArray.find_map

### PR DESCRIPTION
**Pull request by UnixJunkie**
introduced in stdlib since OCaml-4.13.0

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/issues/1045

**Comment by gasche** [comment]
@UnixJunkie did you write this implementation yourself, or did you copy it from the stdlib? If you copied the stdlib implementation, I believe that this should be marked clearly (copying code without referencing the author is, in fact, against the law). One way to mark this is to credit the corresponding commit to the original author of the code: `git commit --author "..."` (in this case, I think it is Nicolás Ojeda Bär). When you make changes to someone else's implementation, you can use a `Co-authored-by: ...` line in the commit message (I would use the original author in the `--author` line, and then `Co-authored-by: <myself>`).

**Comment by gasche** [comment]
One other reason to be explicit when the code is copied from the stdlib is that it helps reviewing, other people can focus on the commits that provide new or modified implementations.

**Comment by UnixJunkie** [comment]
The implementation and ocamldoc was copied from the stdlib.
The tests are mine, same for some boilerplate code.
I am OK to put a one-liner comment to say that it comes from the stdlib of 4.13.0 and also
mention it in the ChangeLog.
However, having to go find the author of each new functionality would be quite annoying.

**Pull request merged**
