### PR TITLE
Provide BatList.cartesian_product_(iter|fold)

### PR DESCRIPTION
**Pull request by fccm**
You should merge #998 first before this one.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I personally don't vouch for this PR.
Other maintainers are welcome to come and rescue it if they feel like so.

**Comment by fccm** [comment]
OK, I can still copy it in my own projects.
I thought it could maybe be useful, while in *game-dev* these are iterators that are very and often useful, like for example to check interactions between every enemies with every player bullets.
But never mind, someone looking for it can find these in containers.

**Comment by gasche** [comment]
What is the performance difference between

```
List.cartesian_product_iter (fun a b -> ...) la lb
```

and 

```
la |> List.iter @@ fun a ->
lb |> List.iter @@ fun b ->
....
```

?

**Comment by UnixJunkie** [comment]
@fccm all against all tests are very costly. You should probably use some smarter collision detection data-structure / algorithms.
Usually, this topic is covered in computer graphics books, e.g. because of needs in ray-tracing.

**Comment by gasche** [comment]
To rephrase my point: my impression is that `cartesian_iter` and `cartesian_fold` are unnecessary because they can be simply written as two nested iterations on the lists. Having a function to compute the cartesian product is difficult to express as a tail-recursive computation, so it makes sense to provide it. This being said, in the `_iter` and `_fold` cases I have not actually measured the different, so I might be wrong; I think the onus to do this would be on @fccm, and he may even find (through this experiment) that he himself doesn't need those functions after all.

**Comment by fccm** [comment]
> To rephrase my point: my impression is that `cartesian_iter` and `cartesian_fold` are unnecessary because they can be simply written as two nested iterations on the lists. Having a function to compute the cartesian product is difficult to express as a tail-recursive computation, so it makes sense to provide it. This being said, in the `_iter` and `_fold` cases I have not actually measured the difference, so I might be wrong; I think the onus to do this would be on @fccm, and he may even find (through this experiment) that he himself doesn't need those functions after all.

Yes, you're right. It's just that nesting two `List.fold_left` is not that easy to figure out for a beginner, that sometimes even find difficult to use a single `List.fold_left`.

**Pull request closed without merging**
