### PR TITLE
Map.pop_min_binding

### PR DESCRIPTION
**Pull request by UnixJunkie**
reflection of BatSet.pop_min into Map

### CODE REVIEW

**Comment by UnixJunkie** [comment]
If this is OK, I will send the pop_max equivalent

**Comment by UnixJunkie** [comment]
I sent pop_max also, finally.

**Comment by gasche** [comment]
There is a conflict between this pull-request and #634 as both define the `get_root` function. Could you rebase this pull request on top of the current trunk, and check that it still compiles and passes the tests?

**Comment by UnixJunkie** [comment]
I'll try.

**Comment by UnixJunkie** [comment]
This is here: https://github.com/ocaml-batteries-team/batteries-included/pull/637

**Pull request closed without merging**
