### PR TITLE
A couple of improvements to Array.insert

### PR DESCRIPTION
**Pull request by murmour**
Self-explanatory changes are separated into two commits.

### CODE REVIEW

**Comment by gasche** [comment]
The Change entry suggests that you print a refine message on *negative indices*, but that is not the case, you refined the general message to point out that the failing function is `Array.insert` (there is no specific message on underflows as opposed to overflows). Otherwise the patch is correct and an improvement. Should we merge as-is, or do you wish to clarify the change entry?

**Comment by murmour** [comment]
> The Change entry suggests that you print a refine message on negative indices, but that is not the case, you refined the general message to point out that the failing function is Array.insert.

Got it. I agree that the wording could be more precise.

I've changed "negative" to "invalid".

**Comment by gasche** [comment]
Merged, thanks.

**Comment by UnixJunkie** [comment]
the valid range is [0..n], not [0..n-1]?

**Comment by gasche** [comment]
This confused me at first, but yet. The returned array has size (n+1), and inserting at position n is supported (it puts the element at the end of the new array). The code is correct and this use-case is tested. It may have been emphasized by the documentation, but I didn't want to add unrelated concerns to the PR.

**Comment by UnixJunkie** [comment]
OK then, it's an insert that can append at the end of the array, sorry for the noise.

**Pull request merged**
