### PR TITLE
added BatList.fold_while

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by thizanne** [comment]
Without introducing an additional mutable state, this signature doesn't
allow you to, say, "sum the elements of the list until the sum is greater
than 42" : the predicate can only check the list element value. I'd say
having the more expressive version is valuable.

**Comment by UnixJunkie** [comment]
@thizanne what is the signature that you are thinking about?

**Comment by thizanne** [comment]
You have several ways of doing it, and quoted one in #888 : 

```val fold_while : ('a -> 'b -> 'a * [ `Stop | `Continue ]) -> 'a -> 'b t -> 'a```

I'm not sure why you find it "not explicit enough". The important part is that the function that decides when the fold has to be stopped has access to the value of the accumulator.

Iterating from your proposal:
```val fold_while : ('a -> bool) -> ('acc -> 'a -> 'acc) -> 'acc -> 'a list -> 'acc * 'a list```

We can add this information (the value of the accumulator) to the predicate:
```val fold_while : ('acc -> 'a -> bool) -> ('acc -> 'a -> 'acc) -> 'acc -> 'a list -> 'acc * 'a list```

Then instead of two functions that take the same parameters, we require one function that will return a tuple. This has several advantages: it makes it explicit in the type that these operations (the construction of the accumulator and the predicate testing) are being done on the same operands, and since they may do the same computation, it's more convenient to define them as one function rather than to artificially split it:
```val fold_while : ('acc -> 'a -> bool * 'acc) -> 'acc -> 'a list -> 'acc * 'a list```

And you get the function of Containers except it uses `bool` instead of ```[`Stop | `Continue]``` (which is a design choice, I personally like the latter more but we should be consistent with other functions of that kind in batteries -- I didn't check).

**Comment by UnixJunkie** [comment]
Ok, got it.
I will update the PR.

**Comment by UnixJunkie** [comment]
I updated the PR.

**Comment by UnixJunkie** [comment]
Anybody to review and merge this?

**Pull request merged**
