### PR TITLE
Adds make functions in BatTuple

### PR DESCRIPTION
**Pull request by thizanne**
TupleN.make takes n arguments and builds a n-tuple.

No big stuff, but they can be useful e.g. as parameters of other functions, especially since `( , )` is no valid syntax.

Maybe `make` is not the better name: I also have in mind `build` and `create`, and have no idea which one (or which other one) is better.

### CODE REVIEW

**Comment by gasche** [comment]
The patch seems fine and `make` is a good name (in the stdlib `create` is for creating uninitialized structures). Could you add an entry to the changelog? This was suggested by @UnixJunkie to decrease the work at release time. Write what you would like users to read in the release announcement (short, but lists all the new functions).

**Comment by UnixJunkie** [comment]
:+1:

**Comment by thizanne** [comment]
What is supposed to be in the version line ? I assumed `NEXT_RELEASE` was fine.

**Comment by gasche** [comment]
Yes, this is fine, thanks!

**Pull request merged**
