### PR TITLE
BatPp

### PR DESCRIPTION
**Pull request by UnixJunkie**
Now, even Batman has an OCaml preprocessor.

This might just do what batteries need.
I don't guarantee it is totally correct.
I just did some toy tests.

Feedback is welcome. I am not a compiler guy, please don't lough at how I parse things.
:D

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/ocaml-batteries-team/batteries-included/issues/658

**Comment by gasche** [comment]
This is already done in [build/prefilter.ml](https://github.com/ocaml-batteries-team/batteries-included/blob/ab4ada0/build/prefilter.ml).

**Comment by UnixJunkie** [comment]
Mine doesn't require the str library.
I will test it more and might add some interesting features.
Then, I will submit again to batteries.

**Comment by gasche** [comment]
The main problem with these preprocessors is (not the use of Str but) the fact that their directives are invalid OCaml syntax. I think it would be worth trying to change the preprocessor syntax to use OCaml comments, for example `(*#V<=4.10#*)`, instead of the current syntax `##V<=4.10##`.

**Pull request closed without merging**
